--- 
authlogic: 
  :options: 
    :version: ~> 2.0
mislav-will_paginate:
  :options:
    :version: ~> 2.2
    :lib: will_paginate
    :source: http://gems.github.com
jscruggs-metric_fu:
  :options:
    :version: ~> 1.1
    :lib: metric_fu
    :source: http://gems.github.com 
binarylogic-searchlogic:
  :options:
    :lib: searchlogic
    :source: http://gems.github.com
    :version: ~> 2.0
justinfrench-formtastic:
  :options:
    :lib: formtastic
    :source: http://gems.github.com
haml:
  :options:
    :version: ~> 2.2
  :if: template_engine == "haml" || design == "compass"
chriseppstein-compass:
  :options:
    :lib: compass
    :source: http://gems.github.com
  :if: design == "compass"
chriseppstein-compass-960-plugin:
  :options:
    :lib: ninesixty
    :source: http://gems.github.com
  :if: "design == 'compass' && compass_css_framework =~ /960/"
josevalim-inherited_resources:
  :options:
    :lib: inherited_resources
    :source: http://gems.github.com
    :version: >= 0.9.0

# development only
cwninja-inaction_mailer: 
  :options:
    :lib: inaction_mailer/force_load
    :source: http://gems.github.com
    :env: development
ffmike-query_trace:
  :options:
    :lib: query_trace
    :source: http://gems.github.com
    :env: development

# test only
ffmike-test_benchmark:
  :options:
    :lib: test_benchmark
    :source: http://gems.github.com
    :env: test
webrat:
  :options:
    :env: test
rr:
  :options:
    :version: ">=0.10.2"
    :env: test
  :if: @mocking == "rr"